/*
 * Copyright (c) 2015 Nikolay Zapolnov (zapolnov@gmail.com).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.zapolnov.buildsystem.plugins.metacompiler;

import com.zapolnov.buildsystem.project.ProjectDirective;
import com.zapolnov.buildsystem.project.ProjectVisitor;
import com.zapolnov.buildsystem.project.directives.SourceFilesDirective;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** A "virtual" directive that injects source files generated by the meta-compiler into the project. */
public final class MetaCompilerSourceFilesDirective extends ProjectDirective
{
    /** List of source files. */
    private final List<File> sourceFiles = new ArrayList<>();

    /** Constructor. */
    public MetaCompilerSourceFilesDirective()
    {
    }

    /**
     * Adds source file to the list.
     * @param file Path to the source file.
     */
    public void addFile(File file)
    {
        sourceFiles.add(file);
    }

    @Override public void visit(ProjectVisitor visitor)
    {
        visitor.visitSourceFiles(new SourceFilesDirective(Collections.unmodifiableList(sourceFiles), false));
    }
}
